# Generated by Django 5.0.3 on 2024-03-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task2", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancy",
            options={"verbose_name": "Vacancy", "verbose_name_plural": "Vacancies"},
        ),
        migrations.AlterModelTable(
            name="vacancy",
            table="vacancy",
        ),
    ]
