# Generated by Django 5.0.3 on 2024-03-30 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountyLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.ImageField(upload_to="team_avatars")),
                ("Country", models.CharField(max_length=100)),
                ("League", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Country League",
                "verbose_name_plural": "Country Leagues",
                "db_table": "country_leagues",
            },
        ),
        migrations.CreateModel(
            name="SportType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Sport Type",
                "verbose_name_plural": "Sport Types",
                "db_table": "sport_types",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.ImageField(upload_to="team_avatars")),
                ("name", models.CharField(max_length=100)),
                (
                    "sport_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task4.sporttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "db_table": "teams",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1_score", models.IntegerField()),
                ("team2_score", models.IntegerField()),
                ("match_date", models.DateTimeField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("started", "started"),
                            ("finished", "finished"),
                            ("upcoming", "Upcoming"),
                        ],
                        default="upcoming",
                        max_length=10,
                    ),
                ),
                (
                    "country_league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task4.countyleague",
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team1",
                        to="task4.team",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team2",
                        to="task4.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "db_table": "matches",
            },
        ),
    ]
